# Generated by Django 5.1.6 on 2025-02-23 21:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=255, unique=True, verbose_name='Name ES')),
                ('load_units', models.CharField(choices=[('KG', 'kg'), ('KM', 'km'), ('M', 'm'), ('MINUTES', 'min'), ('SECONDS', 'sec'), ('BODY_WEIGHT', 'bod')], verbose_name='Load units')),
                ('explanation', models.TextField(blank=True, verbose_name='Explanation')),
                ('explanation_es', models.TextField(blank=True, verbose_name='Explanation ES')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=255, unique=True, verbose_name='Name ES')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='SubMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=255, unique=True, verbose_name='Name ES')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('excercices', models.ManyToManyField(related_name='training_session', to='training.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(blank=True, null=True, related_name='exercise', to='training.muscle'),
        ),
        migrations.CreateModel(
            name='MuscularGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('name_es', models.CharField(max_length=255, unique=True, verbose_name='Name ES')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image')),
                ('muscles', models.ManyToManyField(related_name='muscular_group', to='training.muscle')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscular_group',
            field=models.ManyToManyField(blank=True, null=True, related_name='exercise', to='training.musculargroup'),
        ),
        migrations.AddField(
            model_name='muscle',
            name='submuscles',
            field=models.ManyToManyField(blank=True, null=True, related_name='muscle', to='training.submuscle'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='submuscles',
            field=models.ManyToManyField(blank=True, null=True, related_name='exercise', to='training.submuscle'),
        ),
        migrations.CreateModel(
            name='TrainingSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_exercise_record', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Date')),
                ('repetitions', models.PositiveIntegerField(verbose_name='Repetitions')),
                ('load', models.PositiveIntegerField(verbose_name='Load')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_record', to='training.exercise', verbose_name='Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_record', to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_record', to='training.trainingsessionrecord')),
            ],
        ),
        migrations.CreateModel(
            name='CustomTrainingSession',
            fields=[
                ('trainingsession_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='training.trainingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_training_session', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('training.trainingsession',),
        ),
    ]
