# Generated by Django 5.1.6 on 2025-03-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(blank=True, related_name='exercise', to='training.muscle'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscular_group',
            field=models.ManyToManyField(blank=True, related_name='exercise', to='training.musculargroup'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='submuscles',
            field=models.ManyToManyField(blank=True, related_name='exercise', to='training.submuscle'),
        ),
        migrations.AlterField(
            model_name='muscle',
            name='submuscles',
            field=models.ManyToManyField(blank=True, related_name='muscle', to='training.submuscle'),
        ),
    ]
