# Generated by Django 5.1.7 on 2025-03-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_exercise_image_url_alter_exercise_muscles_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='exerciserecord',
            options={'ordering': ['exercise__name', 'date']},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='explanation_es',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='muscle',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='musculargroup',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='submuscle',
            name='name_es',
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
