# Generated by Django 5.1.7 on 2025-03-23 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_alter_exercise_options_alter_exerciserecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciserecord',
            name='training_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_record', to='training.trainingsessionrecord', verbose_name='Training Session'),
        ),
    ]
