# Generated by Django 5.1.7 on 2025-03-23 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_alter_exerciserecord_training_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingsession',
            name='excercices',
        ),
        migrations.CreateModel(
            name='ExerciseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(blank=True, default=0, verbose_name='Sets')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_template', to='training.exerciserecord', verbose_name='Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSessionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('excercices', models.ManyToManyField(related_name='training_session_template', through='training.ExerciseTemplate', to='training.exerciserecord')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_session_template', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercisetemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_template', to='training.trainingsessiontemplate', verbose_name='Training Session template'),
        ),
        migrations.DeleteModel(
            name='CustomTrainingSession',
        ),
        migrations.DeleteModel(
            name='TrainingSession',
        ),
    ]
