# Generated by Django 5.1.7 on 2025-03-23 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_remove_trainingsession_excercices_exercisetemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisetemplate',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_template', to='training.exercise', verbose_name='Exercise'),
        ),
        migrations.AlterField(
            model_name='trainingsessiontemplate',
            name='excercices',
            field=models.ManyToManyField(related_name='training_session_template', through='training.ExerciseTemplate', to='training.exercise'),
        ),
    ]
