# Generated by Django 5.1.7 on 2025-03-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0006_alter_exercisetemplate_exercise_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercisetemplate',
            options={'ordering': ['template__name']},
        ),
        migrations.AlterModelOptions(
            name='trainingsessiontemplate',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='trainingsessiontemplate',
            old_name='excercices',
            new_name='exercises',
        ),
    ]
