# Generated by Django 5.1.7 on 2025-03-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_alter_exercisetemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciserecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='trainingsessiontemplate',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
    ]
