# Generated by Django 5.2.1 on 2025-08-20 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0009_alter_exerciserecord_load_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Weight'),
        ),
    ]
