# Generated by Django 5.2.1 on 2025-08-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0010_alter_weight_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciserecord',
            name='load',
            field=models.FloatField(verbose_name='Load'),
        ),
    ]
